apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: nginx-ingress
spec:
  defaultBackend:
    service:
      name: nginx-ingress-service
      port:
        number: 80
  rules:
  - host: nginx
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-ingress-service
            port:
             number: 80
